### ISSUE TITLE
USB frequency counter (PCB)

### ISSUE THREAD

**Issue by swharden** [swharden/AVR-projects#1]
Create a USB frequency counter based on an ATMega328 and 20SN74LV8154 and have the output send data to a PC with an FTDI chip (FT232 or similar). 
* This would be a PCB version of something similar to [this project](https://github.com/swharden/AVR-projects/tree/master/ATMega328%202016-09-04%20SN74LV8154)
* The gate should come from a 10 MHz signal
  * the 10 MHz can be internally generated or externally provided
  * if the MCU is clocked at 10 MHz, the clock output is a great internal signal
  * the division should be controlled allow multiple gate frequencies (1 Hz and 10 Hz seem useful)
* Consider allowing it to interface a LED or LCD to display frequency without a computer.
* What's the advantage of this over all the [cheap frequency counters on ebay](https://www.ebay.com/sch/i.html?_nkw=frequency+counter)? 
  * USB connectivity which allows for logging and graphing over time.
  * accepting a 10MHz input allows connection to cheap GPS reference signals
* use all SMD parts (SOIC and 0805)
* Screen will be a SPI-controlled 8 digit display [like this](https://www.amazon.com/dp/B07CL2YNJQ)

***EDIT: this discussion became its own project: ~~[USB Frequency Counter](https://github.com/swharden/AVR-projects/tree/master/ATMega328%202019-07-05%20USB%20counter)~~ https://github.com/swharden/USB-Counter***

**Comment by ravimiranda** [comment]
~Screen suggestions, are either 2x16 LCD display or the TFT screens. I do not believe that there is a lot of information to be displayed?
~to make it easy for enthusiasts to build 1206 parts would be useful
~If it was self contained, there may be no need for a computer interface except for logging maybe?
~Use the GPS 1pps signal to gate seems a good option, but getting a OXCO is additional cost?
~Using a GPS unit that produces a 10Khz signal would help, but cost again
Just my thoughts though :-)

**Comment by swharden** [comment]
> ~Screen suggestions, are either 2x16 LCD display or the TFT screens. I do not believe that there is a lot of information to be displayed?

I'll have it interface  SPI-driven 7-segment 8-character display modules that are super cheap on Amazon and ebay (example: https://www.amazon.com/dp/B07CL2YNJQ). I've used these before and they look great ([see this abandoned project video](https://youtube.com/video/r4ebfhEWejI))

This puts the price point far less than $4 per screen, and there are mounting screw holes and an easy way to run wires between the counter PCB and the display.

> ~to make it easy for enthusiasts to build 1206 parts would be useful.

0805 is pretty similar to 1206 and in my experience parts are easier to source. All my component stocks are 0805 too, so I'm pretty biased toward it. The PCB will be open source so it'll be easy to change for anyone who really wants to use different components.

> ~If it was self contained, there may be no need for a computer interface except for logging maybe?

I'm thinking a micro USB port could provide power and logging. I'll add 5V and GND solder pads to make it easy to power without a USB port for self-contained operation.

> ~Use the GPS 1pps signal to gate seems a good option, but getting a OXCO is additional cost?

I forgot that most GPS outputs are 1Hz. Many $20-$40 eBay OCXOs are 10MHz which would have to be divided by ten million to become 1Hz. 

I'm thinking of adding a divide-by-ten-million circuit on the board, clocking the microcontroller at 10MHz, then running the MCU clock output through the divider to produce the 1Hz gate. The user could use a solder jumper to optionally supply their own 10Mhz or 1Hz signal to trigger the gate.

@ravimiranda what do you think of these ideas? I'd love to finish the part selection and PCB design this weekend.

**Comment by ravimiranda** [comment]
@swharden, Yes your ideas are good. 
Addition of a Microchip charger for a LiPo battery, but then current drain would be high IMHO? Maybe not in this version? 
Yes, an open source idea would be excellent. jumper for OXCO would be perfect.
Thank you!

**Comment by ravimiranda** [comment]
@swharden  I just had a thought, what if we used an Arduino Nano for this? The USB interface would then be ready to use, this would be instead of the ATMEGA328P? Programming via the Arduino interface/programmer then is a doddle?
Is this doable?
Many thanks!

**Comment by swharden** [comment]
* I'm shooting for minimal complexity, minimal cost, and a self-contained board. 
  * I don't see much advantage using Arduino here. If I laid out an Arduino board it would look very similar to this one. If I used a pre-made Arduino board, now we have a 2-PCB device.
  * A LiPo battery/charger would be interesting, but added cost and complexity. I'd love to keep this small and cheap!

**Comment by ravimiranda** [comment]
Minimal cost and complexity is great. 
Yes the layout for both would be similar, I just thought that the Arduino Nano would be a pluggable board and that would remove the FT Chip. Maybe the overall size could be smaller? I'm not sure if the Nano has a onboard crystal, but I'll go with what you think is best!

**Comment by swharden** [comment]
I think this design does all the things.
* the microcontroller runs at 10MHz by default
* the microcontroller generates a 1Hz gate signal in software
* user can override 1Hz gate if desired
* user can use 10MHz reference by sending it right into XTAL1 (replacing the crystal)
  * this signal will be AC-coupled, so it should probably be converted to TTL first

remaining issue: convert input from AC to TTL

![image](https://user-images.githubusercontent.com/4165489/60747034-9525e700-9f50-11e9-8ed6-1aadb8a2645a.png)

**Comment by ravimiranda** [comment]
Here's a thought, what if we provided PWR pins to drive the external 10Mhz OXCO.  This would allow for a 10MHz OXCO to be added and power could be sourced from this board? The assembly could be fitted inside a case.

**Comment by swharden** [comment]
> Here's a thought, what if we provided PWR pins to drive the external 10Mhz OXCO. This would allow for a 10MHz OXCO to be added and power could be sourced from this board? The assembly could be fitted inside a case.

I guess the "external power" solder pads could work in either direction! When plugged into a USB port, they could supply power to whatever's connected there... but those OCXOs draw a lot of current. I'm not sure if a USB port can supply that.

**Comment by ravimiranda** [comment]
Yes, just checked that, the USB will not be able to do that, my bad

**Comment by swharden** [comment]
I'd like to buffer the RF input though... not sure which chip I should use for that. I'm shooting for simple and cheap! The 74hc240 is my go-to but we wouldn't be using most of the gates...

**Comment by ravimiranda** [comment]
Transistor based buffer? Would that work?

**Comment by swharden** [comment]
> Transistor based buffer? Would that work?

Yeah, that sounds like a better idea than a chip especially since there's just 1 signal to buffer.

This design would be really sensitive, but it would oscillate without an input signal. I wonder if that behavior is desirable, or if I should make a buffer that's less sensitive but at least outputs 0 when no signal is applied?

![image](https://user-images.githubusercontent.com/4165489/60747416-f6e75080-9f52-11e9-944b-65676ab0713b.png)

**Comment by ravimiranda** [comment]
A common version used earlier is here:
https://electronics.stackexchange.com/questions/98792/can-i-use-mic-to-input-frequency-meter-circuit
or
http://electronics-diy.com/electronic_schematic.php?id=550

**Comment by swharden** [comment]
> A common version used earlier is here:
> https://electronics.stackexchange.com/questions/98792/can-i-use-mic-to-input-frequency-meter-circuit
> or
> http://electronics-diy.com/electronic_schematic.php?id=550

The problem I keep running into is that as I make the input buffer more and more complex, it becomes simpler and cheaper just to put a TTL buffer chip in its spot. They're also high-voltage tolerant.

This design is similar to the ones you linked to, but it has no input protection and very high voltage signals could damage it, but it's super cheap and simple to stick in there... especially since I was thinking about not buffering the input signal at all originally =]

![image](https://user-images.githubusercontent.com/4165489/60747772-cf45b780-9f55-11e9-9455-86e6d52fa064.png)

**Comment by swharden** [comment]
I guess input protection isn't that hard to add
![image](https://user-images.githubusercontent.com/4165489/60747862-6874ce00-9f56-11e9-976d-51f701e8b98a.png)

**Comment by ravimiranda** [comment]
IMHO, the diodes 1N4148 provide some level of protection?
http://electronics-diy.com/electronic_schematic.php?id=550
BAV99? in this case. Will the fT of the transistor matter? BFR 106 or equivalent?

**Comment by swharden** [comment]
> ![image](https://user-images.githubusercontent.com/4165489/60747416-f6e75080-9f52-11e9-944b-65676ab0713b.png)

I don't think this configuration should be overlooked! We can add a 100k series input resistor and this will detect any signal you put in it. It will be so sensitive that it will detect noise if no RF input is supplied, but maybe that's not bad? You can just hold it up to a transmitting device and the RF emitted will get picked up by a front-end like this and you can measure its frequency. It's simple/cheap too.

**Comment by swharden** [comment]
In schematic, that looks like this. I may fine-tune the resistor values.
![image](https://user-images.githubusercontent.com/4165489/60748051-09b05400-9f58-11e9-8e8b-31e19d38feac.png)

**Comment by swharden** [comment]
I threw this together:
![image](https://user-images.githubusercontent.com/4165489/60748662-34051000-9f5e-11e9-81f3-be51c90bb355.png)

It's extremely sensitive. Here it is amplifying +/- 100 mV input:
![image](https://user-images.githubusercontent.com/4165489/60748664-3ebfa500-9f5e-11e9-910d-9aca333e2bbf.png)

The input protection is good up to 30V (PPV) input, after which the protection diodes would start to burn. To use this with higher voltages, increase R3 accordingly.

It _will_ self-oscillate and/or amplify whatever RF is in the room if no input is connected.

![image](https://user-images.githubusercontent.com/4165489/60749556-9a436000-9f69-11e9-98b5-92f6246dce7b.png)

**Comment by swharden** [comment]
All the files and notes are here:
https://github.com/swharden/AVR-projects/tree/master/ATMega328%202019-07-05%20USB%20counter

What do you think? Ready to fabricate?
![image](https://user-images.githubusercontent.com/4165489/60759256-20a28500-9ff0-11e9-98ef-d135217488a2.png)

**Comment by ravimiranda** [comment]
Excellent, but might be worth adding the mounting screw holes for this?
But, yes good to go.

**Comment by swharden** [comment]
[Onno Hoekstra](https://www.qsl.net/pa2ohh/) suggested I add an optional prescaler to the front-end to allow measurement of higher frequency signals: https://doc.lagout.org/electronics/doc/ic_various/SAB6456.PDF

With divide-by-256 enabled, we measure GHz signals with this counter.

That part isn't on mouser or digikey, but perhaps we could find a cheap alternative.

EDIT: let's use an octal [flip-flop](https://www.mouser.com/ProductDetail/Toshiba/74VHCT574AFTBE?qs=sGAEpiMZZMutXGli8Ay4kK7RahMJNS2Ilmva2pHTI7k%3D) which gets us up to 140MHz

**Comment by ravimiranda** [comment]
Hi Scott
Was away for a few days and time went past so quickly. 
Would the LMX series work?
There are also the Motorola series of prescalers

**Comment by swharden** [comment]
***The USB Counter now has its own project page: 
https://github.com/swharden/USB-Counter***

PCBs came in today so I'll see how far I can get on it this weekend. My LED-blink program is already running which is a good sign, but I haven't interfaced the counter IC yet. 

I'll post updates on the new page.

**Comment by swharden** [comment]
https://github.com/swharden/USB-Counter
![image](https://user-images.githubusercontent.com/4165489/62419305-21f4bb00-b64b-11e9-996e-bfbbf61cb5d9.png)
