### ISSUE TITLE
Solution: How to fix this so it can handle VHF reliably Re: ATMega328 2016-09-04 SN74LV8154

### ISSUE THREAD

**Issue by freemo** [swharden/AVR-projects#2]
Re: ATMega328 2016-09-04 SN74LV8154

Hi, EE here and took a quick glance at your project and it was immediately obvious why you struggled with signals above 50 MHz, and its an easy fix so i wanted to explain it here.

The solution itself is simple, you mentioned you were using 50 Ohm feed lines. That means you need to also add a 50 Ohm resistor from pin 1 to ground and from pin 7 to ground on your sn74lv8154 chip. Problem solved.

So I want to explain why though just so you can understand this. This will allow your load (the frequency counter) to present as a 50 Ohm impedance, this will mean your load will match your feedline impedance and hopefully your signal generator as well (Which should be a 50 Ohm source, which it likely is). The way you have it designed here your frequency counter presents as a high impedance load, and is thus drastically mismatched with the rest of the system. This means any signal that come in will not actually get into the chip and instead will be reflected back at the source. In turn this will mean the signal will appear very weak and wont trigger a high-low state. The effect of this gets worse with longer feedlines and with higher frequencies, this is why it worked earlier before you moved it to the case.

If you need me to clarify this further just reply with any questions, happy to help explain it.

**Comment by swharden** [comment]
hi @freemo, thank you for your excellent advice!

### Original Project

You are referring to:
https://github.com/swharden/AVR-projects/tree/master/ATMega328%202016-09-04%20SN74LV8154

> The solution itself is simple, you mentioned you were using 50 Ohm feed lines. That means you need to also add a 50 Ohm resistor from pin 1 to ground and from pin 7 to ground on your sn74lv8154 chip.

Indeed, [properly terminating](https://en.wikipedia.org/wiki/Electrical_termination) coax will prevent reflection of the signal. \
I'll add a note to that page to make this clear, thanks for pointing it out!

### Newer Project

Note that the referecned project spawned its own repo:
https://github.com/swharden/USB-Counter

... and reviewing that schematic it looks like the line terminated like you suggest:
![image](https://user-images.githubusercontent.com/4165489/91728773-8f865a00-eb71-11ea-98c6-dfb979772397.png)

**Comment by freemo** [comment]
Wonderful, the new project looks very nice. Glad you figured it out.

**Comment by freemo** [comment]
by the way, thank you for the schematic. I am currently working on V3 of my
ROES meter (has a frequency counter in it but is actually more of a VNA). I
have a small signal amplifier in it but it uses an op-amp. Your design
though might be cheaper with a smaller footprint. Do you know what
frequency range it can handle off hand?

**Comment by swharden** [comment]
> Do you know what frequency range it can handle off hand?

Not really, but I found it easy to simulate so perhaps you could gain insights that way
https://github.com/swharden/AVR-projects/issues/1#issuecomment-508881583

It was suggested I could add a prescaler on the input like [SAB6456](https://doc.lagout.org/electronics/doc/ic_various/SAB6456.PDF) which can accept up to 1GHz, divide by 64 (15.625 MHz), and drive the counter.

Food for thought!

**Comment by freemo** [comment]
Yea my current design will involve either a prescaler or binary counter
once I get to that part. I'm just running out of board realestate so your
small signal amp might save me enough space to fit the rest in. I probably
wont simulate it though i usually solder up a prototype to test, a bit more
accurate. Either way thanks.

If your interested you can check out V1 here, but I havent added the V2 we
are discussing yet: https://git.qoto.org/roes/roes-hardware/
