### ISSUE TITLE
ATMega328 LM75A schematic diagram

### ISSUE THREAD

**Issue by ENG230** [swharden/AVR-projects#3]
can i have the schematic diagram for ATMega328 2017-02-08 i2c LM75A thermometer

**Comment by swharden** [comment]
Hi @ENG230, this is on the main readme - hope it helps!

https://github.com/swharden/AVR-projects/tree/master/ATMega328%202017-02-08%20i2c%20LM75A%20thermometer

![image](https://user-images.githubusercontent.com/4165489/164484181-cef38dcc-9f2a-43ee-9496-64fe15fff3c5.png)
