### ISSUE TITLE
ATMega328 2019-08-04 max7219 7segment display schematic diagram

### ISSUE THREAD

**Issue by ENG230** [swharden/AVR-projects#4]
can i have the ATMega328 2019-08-04 max7219 7segment display schematic diagram?

**Comment by swharden** [comment]
https://github.com/swharden/AVR-projects/tree/master/ATMega328%202019-08-04%20max7219%207segment%20display#wiring

![image](https://user-images.githubusercontent.com/4165489/164541986-59888a7e-5b55-4f51-9cc7-28d5af117a27.png)

**Comment by swharden** [comment]
Related,

* https://github.com/swharden/USB-Counter
* https://github.com/swharden/USB-Counter/tree/master/builds/1.1
* https://swharden.com/blog/2019-08-03-usb-frequency-counter/
